# Generated by Django 3.2.7 on 2021-09-09 18:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchedError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=255)),
                ('error_term', models.CharField(max_length=255)),
                ('possibleCorrections', models.CharField(default='', max_length=255)),
                ('error_sentence', models.CharField(max_length=255)),
                ('error_line_number', models.IntegerField()),
                ('page_url', models.CharField(max_length=255)),
                ('jobId', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
