# Generated by Django 3.2.7 on 2021-09-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spellchecker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchederror',
            old_name='jobId',
            new_name='job_id',
        ),
    ]
